version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/application/init.sql:/data/application/init.sql
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - db

